### ISSUE TITLE
Demo: API calls need to be replaced with static data

### ISSUE THREAD

**Issue by isaacsheyliger** [heyligerjon/crate_frontend#1]
Currently, the pages_demo branch is making calls to API routes. GitHub pages only supports hosting for static sites so we will need to convert these API calls to use demo json data from the album-data.json static file.

Only fetch calls for the blog components should be considered, the digger module is incomplete and not included in the demo currently.

**Comment by abhishek-shivale** [comment]
Hi, can I work on this issue? also can provide more info?
